import { Excercise } from './excercise';

export const EXCERCISES: Excercise[] = [
  { name: 'Aerobic', stepsPerHalfHour: 5350 },
  { name: 'Badminton', stepsPerHalfHour: 3850 },
  { name: 'Beach vollyboll', stepsPerHalfHour: 4400 },
  { name: 'Bordtennis', stepsPerHalfHour: 2500 },
  { name: 'Bowling', stepsPerHalfHour: 2000 },
  { name: 'Boxning', stepsPerHalfHour: 5850 },
  { name: 'Brottning', stepsPerHalfHour: 5200 },
  { name: 'Bugg', stepsPerHalfHour: 4000 },
  { name: 'Crosstrainer', stepsPerHalfHour: 5500 },
  { name: 'Cykla avspänt ca 10 km/h', stepsPerHalfHour: 2950 },
  { name: 'Cykla motionstempo ca 20 km/h', stepsPerHalfHour: 4900 },
  { name: 'Cykling terräng', stepsPerHalfHour: 7350 },
  { name: 'Dans hip hopp', stepsPerHalfHour: 4550 },
  { name: 'Dans motion', stepsPerHalfHour: 4000 },
  { name: 'Dans salsa', stepsPerHalfHour: 3700 },
  { name: 'Fotboll', stepsPerHalfHour: 6350 },
  { name: 'Golf', stepsPerHalfHour: 3100 },
  { name: 'Gympa intensiv', stepsPerHalfHour: 4600 },
  { name: 'Gympa lätt', stepsPerHalfHour: 1950 },
  { name: 'Gympa medel', stepsPerHalfHour: 3300 },
  { name: 'Handboll', stepsPerHalfHour: 5950 },
  { name: 'Hockey', stepsPerHalfHour: 4050 },
  { name: 'Inlines', stepsPerHalfHour: 3450 },
  { name: 'Innebandy', stepsPerHalfHour: 4250 },
  { name: 'Löpning', stepsPerHalfHour: 6400 },
  { name: 'Pilates/Yoga/Gong/Tai Chi', stepsPerHalfHour: 2350 },
  { name: 'Pump', stepsPerHalfHour: 4900 },
  { name: 'Ridning', stepsPerHalfHour: 3500 },
  { name: 'Simning', stepsPerHalfHour: 3750 },
  { name: 'Skidor', stepsPerHalfHour: 6550 },
  { name: 'Slalom', stepsPerHalfHour: 4950 },
  { name: 'Snowboard', stepsPerHalfHour: 4300 },
  { name: 'Spinning', stepsPerHalfHour: 5900 },
  { name: 'Step Up', stepsPerHalfHour: 4600 },
  { name: 'Styrketräning Normal', stepsPerHalfHour: 3900 },
  { name: 'Tennis', stepsPerHalfHour: 4950 },
  { name: 'Vattengymnastik', stepsPerHalfHour: 3400 },
  { name: 'Vattenskidor', stepsPerHalfHour: 4850 },
  { name: 'Vollyboll', stepsPerHalfHour: 3250 }
];
